## This script codes two functions that allow caching of the inverse of a given
## matrix

## makeCacheMatrix accepts a matrix as an argument and returns a list of
## four functions that do one of the following:
##      1. set the value of the matrix
##      2. retrieve the value of the matrix
##      3. set the value of the inverse of the matrix
##      4. retrieve the value of the inverse of the matrix

makeCacheMatrix <- function(x = matrix()) {
  i <<- NULL
  set <- function(y) {
    x <<- y
    i <<- NULL
  }
  get <- function() x
  setinv <- function(inv) i <<- inv
  getinv <- function() i
  list(set = set, get = get, setinv = setinv, getinv = getinv)
}


## cacheSolve takes a list of the kind generated by makeCacheMatrix and checks
## to see if the inverse of the matrix that was used as an argument in
## makeCacheMatrix is stored.  If so, the cacheSolve returns the stored inverse.
## On the other hand, the matrix is retrieved, the inverse of it calculated using
## the solve() function, and cached.

cacheSolve <- function(x, ...) {
        ## Return a matrix that is the inverse of 'x'
  i <- x$getinv()
  if (!is.null(i)) {
    message("getting cached inverse matrix")
    return(i)
  }
  data_matrix <- x$get()
  i <- solve(data_matrix, ...)
  x$setinv(i)
  i
}
